use deno gn to work around gn build failues
FAILED: src/base/environment.o 
/home/linuxbrew/.linuxbrew/opt/llvm/bin/clang++ -MMD -MF src/base/environment.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/environment.cc -o src/base/environment.o
In file included from ../src/base/environment.cc:5:
../src/base/environment.h:11:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~